model_params:
  dqn:
    learning_rate: 0.00001
    buffer_size: 50000
    batch_size: 32
    tau: 1.0
    gamma: 0.995
    train_freq: 4
    gradient_steps: 1
    target_update_interval: 50000
    exploration_fraction: 0.25 
    exploration_initial_eps: 1.0
    exploration_final_eps: 0.05
    max_grad_norm: 10
